### ISSUE TITLE
Customize sparse latent point clouds

### ISSUE THREAD

**Issue by HengyuMeng** [SLIDE-3D/SLIDE#1]
Hi @ZhaoyangLyu， Thank you for your wonderful and impressive work,  and I have a question about customizing sparse latent points.

My question is :
* Can I customize sparse latent point clouds instead of using Position DDPM?
* Then can I use Feature DDPM to reconstruct my custom latent point clouds to dense point clouds(2048)?

I will be grateful if you can answer my questions.

**Comment by ZhaoyangLyu** [comment]
Yes. You can provide the positions of the sparse latent points by yourself, you need to save the positions in an .npz file and then use the file latent_ddpm_keypoint_conditional_generation.py to generate features and reconstruct point clouds following instructions in the Readme.

**Comment by HengyuMeng** [comment]
I see, many thanks for your reply.
