### ISSUE TITLE
No such file or directory: '../data/shapenet_psr/02691156/train.lst'

### ISSUE THREAD

**Issue by HengyuMeng** [SLIDE-3D/SLIDE#2]
Hi@Zhaoyang Lyu, I have successfully followed the steps to configure the environment, 

but when I run the script:

export CUDA_VISIBLE_DEVICES=0 && python point_cloud_generation.py --config ../exps/mesh_overall_ckpts_and_generation_results/latent_position_ddpm_models/add_centroid_to_first_keypoint/airplane/config_standard_attention_batchsize_32_s3_ema_model_keypoint_airplane_02691156.json \
--ckpt ../exps/mesh_overall_ckpts_and_generation_results/latent_position_ddpm_models/add_centroid_to_first_keypoint/airplane/pointnet_ckpt_884999.pkl \
--ema_idx 0 --num_samples 400 --batch_size 200 \
--save_dir ../exps/generated_point_cloud_and_mesh/airplane/centroid

I get the following error:

Petrel oss client is not installed
Petrel oss client is not installed
Using cuda device 0
Generated samples will be saved to ../exps/generated_point_cloud_and_mesh/airplane/centroid/shapenet_psr_generated_data_16_pts.npz
will not repeat the dataset because need to random_subsample
dataset augmentation is False
Traceback (most recent call last):
  File "point_cloud_generation.py", line 129, in <module>
    main(args.ckpt, args.ema_idx, save_dir, diffusion_model=diffusion_model, rank=0, num_gpus=1)
  File "point_cloud_generation.py", line 30, in main
    evaluate_per_rank(net, trainset_config, diffusion_hyperparams, save_dir, train_config['task'], 
  File "/home/hengyumeng/SLIDE/SLIDE/pointnet2/sampling_and_inference/../mesh_evaluation.py", line 57, in evaluate_per_rank
    testloader = get_dataloader(trainset_config_copy, phase='train', rank=rank, world_size=world_size, 
  File "/home/hengyumeng/SLIDE/SLIDE/pointnet2/sampling_and_inference/../dataset.py", line 28, in get_dataloader
    dataset = Shapes3dDataset(args['data_dir'], split=phase, categories=args['categories'], scale=args['scale'], 
  File "/home/hengyumeng/SLIDE/SLIDE/pointnet2/sampling_and_inference/../shapenet_psr_dataloader/shapenet_psr_dataset.py", line 86, in __init__
    models_c = self.text_oss.read(split_file).split('\n')
  File "/home/hengyumeng/SLIDE/SLIDE/pointnet2/sampling_and_inference/../oss_utils/text_oss_io_utils.py", line 38, in read
    with open(path, 'r') as f:
**FileNotFoundError: [Errno 2] No such file or directory: '../data/shapenet_psr/02691156/train.lst'**

I wonder how I should get this file and fix this error. 
 thanks!

**Comment by ZhaoyangLyu** [comment]
Thanks for your interest in our work! You need to download the processed ShapeNet dataset from https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/data/dataset_small_v1.1.zip, unzip it and move it to the folder pointnet2/data.

**Comment by HengyuMeng** [comment]
Thanks for your reply. I've fixed the problem, but it's worth noting that after compression is complete, we need to move all the subfolders in the ShapeNet folder into the shapenet_psr directory.
![1687246691357](https://github.com/SLIDE-3D/SLIDE/assets/84671272/478c8dc3-6a8c-4281-9808-ce78d51d24c7)
